version: '3'

services:
  backend:
    user: "0:0"
    image: docker.artifactory.code.dodiis.mil/cio4/zerotrustprototype/dev/ztp-backend:latest
    build: .
    environment:
      DOMAIN_NAME: localhost
      KEYCLOAK_HOST: http://localhost:8080
      KEYCLOAK_CLIENT_SECRET: BJ8BFHBhs90zbwfgKW705QOOxsxAc4lx
    network_mode: host
    ports:
      - 8000:8000
    depends_on:
      - keycloak
      - db
      - opa
    volumes:
      - ./apps:/app/apps:z
      - ./data:/app/data:z
      - ./ztp_browser:/app/ztp_browser:z
  keycloak:
    user: "0:0"
    container_name: jboss_keycloak
    image: jboss/keycloak:latest
    network_mode: host
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
      JAVA_OPTS: "-Dkeycloak.import=/config/realm-export.json -Dcom.redhat.fips=false"
    volumes:
      - ./docker-compose/keycloak/config:/config:z
      - ./docker-compose/keycloak/themes/base2:/opt/jboss/keycloak/themes/base2
    ports:
      - 8080:8080
  db:
    user: "0:0"
    image: docker.io/postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGSSLMODE: disable
      POSTGRES_HOST_AUTH_METHOD: trust
  opa:
    user: "0:0"
    image: openpolicyagent/opa:latest-rootless
    restart: always
    command:
      - run
      - --server
      - --h2c
      - --log-level=debug
      - /policies
    environment:
      - POLICY_PATH=/v1/data/policy
    volumes:
      - ./docker-compose/opa/policies:/policies:z
      - ./docker-compose/opa/logs:/logs:z
    ports:
      - 8181:8181
