apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ztp.tls.certName }}
  namespace: istio-system
spec:
  secretName: {{ .Values.ztp.tls.certName }}
  dnsNames: {{ .Values.ztp.tls.dnsNames }}
  issuerRef:
    name: {{ .Values.ztp.tls.issuerName }}
    