apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app: {{ .Chart.Name }}-backend
spec:
  ports:
    - port: {{ .Values.backend.service.port }}
      name: http
  selector:
    app: {{ .Chart.Name }}-backend
