version: '3'

services:
  keycloak:
    container_name: keycloak
    user: "0:0"
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
      JAVA_OPTS: "-Dkeycloak.import=/config/realm-export.json -Dcom.redhat.fips=false"
    volumes:
      - ./keycloak/config:/config:z
    ports:
      - 8080:8080
  db:
    container_name: postgres
    user: "0:0"
    image: docker.io/postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGSSLMODE: disable
      POSTGRES_HOST_AUTH_METHOD: trust
  opa:
    container_name: opa
    user: "0:0"
    image: openpolicyagent/opa:latest-rootless
    restart: always
    command:
      - run
      - --server
      - --h2c
      - --log-level=debug
      - /policies
    environment:
      - POLICY_PATH=/v1/data/policy
    volumes:
      - ./opa/policies:/policies:z
      - ./opa/logs:/logs:z
    ports:
      - 8181:8181
